version: '2'
services:
  php:
    build: ./docker/php
    # image: yiisoftware/yii2-php:7.1-apache
    env_file:
      - .env
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: on-failure

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: on-failure
